import discord

async def helpcommand(client, message):
    messagestring = 'Commands:\n'
    messagestring += '!loveletter - Starts the game.\n'
    messagestring += '!loveletter extended - Starts the game with up to 9 players.\n'
    messagestring += '!help - Gives you a list of commands.\n'
    messagestring += '!rules - Gives you a list of rules.\n'
    messagestring += '!start - Start playing with the current playerlist.\n'
    messagestring += '!stop - End the currently running game.\n'
    messagestring += '!join - Used to join the game during the login phase.\n'
    messagestring += '!quit - Used to quit the game during the login phase.\n'
    messagestring += '!spy - Play the Spy.\n'
    messagestring += '!guard @example num - Play the Guard, targeting @example and guessing number num.\n'
    messagestring += '!priest @example - Play the Priest, targeting @example.\n'
    messagestring += '!baron @example - Play the Baron, targeting @example.\n'
    messagestring += '!handmaid - Play the Handmaid.\n'
    messagestring += '!prince @example - Play the Prince, targeting @example.\n'
    messagestring += '!chancellor - Play the Chancellor.\n'
    messagestring += '!king @example - Play the King, targeting @example.\n'
    messagestring += '!countess - Play the Countess.\n'
    messagestring += '!princess - Play the Princess.'
    await message.channel.send(messagestring)

async def rules(client, message):
    messagestring = 'Object of the Game:\n'
    messagestring += 'In the wake of the arrest of Queen Marianna for high treason, none was more heartbroken than her daughter, Princess Annette. Suitors throughout the City-State of Tempest sought to ease Annette\'s sorrow by courting her to bring some joy into her life.\n'
    messagestring += 'You are one of these suitors, trying to get your love letter to the princess. Unfortunately, she has locked herself in the palace, so you must rely on intermediaries to carry your message.\n'
    messagestring += 'During the game, you hold one secret card in your hand. This is who currently carries your message of love for the princess.\n'
    messagestring += 'Make sure that the person closest to the princess holds your love letter at the end of the day, so it reaches her first!\n'
    messagestring += 'Game Play:\n'
    messagestring += 'Love Letter is played in a series of rounds. Each round represents one day. At the end of each round, one player\'s letter reaches Princess Annette, and she reads it.\n'
    messagestring += 'When she reads enough letters from one suitor, she becomes enamored and grants that suitor permission to court her. That player wins the princess\'s heart and the game.\n'
    messagestring += 'Taking a Turn:\n'
    messagestring += 'On your turn, draw the top card from the deck and add it to your hand. Then choose one of the two cards in your hand and discard it face up in front of you. Apply any effect on the card you discarded. You must apply its effect, even if it is bad for you.\n'
    messagestring += 'All discarded cards remain in front of the player who discarded them. Overlap the cards so that it\'s clear in which order they were discarded. This helps players to figure out which cards other players might be holding.\n'
    messagestring += 'Once you finish applying the card\'s effect, the turn passes to the player on your left.\n'
    messagestring += 'Out of the Round:\n'
    messagestring += 'If a player is knocked out of the round, that player discards the card in their hand face up (do not apply the card\'s effect) and takes no more turns until next round.\n'
    await message.channel.send(messagestring)
    messagestring = 'End of a Round:\n'
    messagestring += 'A round ends if the deck is empty at the end of a turn. The royal residence closes for the evening, the person closest to the princess delivers the love letter, and Princess Annette retires to her chambers to read it.\n'
    messagestring += 'All players still in the round reveal their hands. The player with the highest ranked person wins the round. In case of a tie, the player who discarded the highest total value of cards wins.\n'
    messagestring += 'A round also ends if all players but one are out of the round, in which case the remaining player wins.\n'
    messagestring += 'The winner receives a token of affection. Shuffle all 21 cards together, and play a new round following all of the setup rules.\n'
    messagestring += 'The winner of the previous round goes first, because the princess speaks kindly of them at breakfast.\n'
    messagestring += 'End of the game:\n'
    messagestring += 'A player wins the game after winning a number of tokens based on the number of players:\n'
    messagestring += '2 Players: 7 tokens\n'
    messagestring += '3 Players: 5 tokens\n'
    messagestring += '4 players: 4 tokens\n'
    messagestring += '5 or 6 players: 3 tokens\n'
    await message.channel.send(messagestring)
    messagestring = 'Cards:\n'
    messagestring += '9: Princess\n'
    messagestring += 'If you play or discard the Princess, you are out of the round.\n'
    messagestring += '8: Countess\n'
    messagestring += 'If you have the Countess and either the King or Prince in your hand, you must discard the Countess.\n'
    messagestring += '7: King\n'
    messagestring += 'Trade hands with a player of your choice. If all other players are protected by the Handmaid, this card is wasted.\n'
    messagestring += '6: Chancellor\n'
    messagestring += 'Draw two cards from the deck and choose which of the three cards you wish to keep. Place the two other cards at the bottom of the deck in whichever order you choose.\n'
    messagestring += 'If there is only one card remaining in the deck, draw only that card and return the card you do not wish to keep. If there are no cards in the deck this card is wasted.\n'
    messagestring += '5: Prince\n'
    messagestring += 'Choose a player. That player must discard their card and draw a new card. If there are no cards left in the deck, they draw the burnt card. You may target yourself with this action.\n'
    messagestring += '4: Handmaid\n'
    messagestring += 'If played, you cannot be targeted by any action until the start of your next turn.\n'
    messagestring += '3: Baron\n'
    messagestring += 'Compare hands with a player of your choice. The player with the lower card is out of the game. If it is a tie, nothing happens. If all other players are protected by the Handmaid, this card is wasted.\n'
    messagestring += '2: Priest\n'
    messagestring += 'Choose a player. You may look at their card. If all other players are protected by the Handmaid, this card is wasted.\n'
    messagestring += '1: Guard\n'
    messagestring += 'Choose a player and guess a number. If your target\'s card has that number, they are out of the game. You may not guess the number 1. If all other players are protected by the Handmaid, this card is wasted.\n'
    messagestring += '0: Spy\n'
    messagestring += 'If, at the end of the round, you are the only remaining player to have played or discarded a Spy, you gain one Favour Token. This does not count as winning the round.'
    await message.channel.send(messagestring)
